version: '3.8'

services:
  # Vector Database (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # API Portu
      - "6334:6334" # GRPC Portu
    volumes:
      - ./qdrant_storage:/qdrant/storage # We write to disk (next to) to prevent data loss
    restart: always
